"""remove new column

Revision ID: d992ac492ccd
Revises: 91420fd462c9
Create Date: 2025-03-07 11:01:47.397990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd992ac492ccd'
down_revision: Union[str, None] = '91420fd462c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_date', 'new_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_date', sa.Column('new_column', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
